### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by iaminamcom** [mhanberg/jekyll-tailwind-starter#13]
Hi I've been using this starter for one of my website. Problem is that I can't install and run Paginating both latest v2 and the older version.

I install them like `gem install jekyll-paginate` and add them in Gemfile as well as in _config file but it's not either giving error not showing the result. The problem is, I can't understand the way you configured it. 
Can you please explain further?

**Comment by mhanberg** [comment]
I’ve never used that plugin before, so I don’t know how it works. 

I would suggest referencing the jekyll docs: https://jekyllrb.com/docs/pagination/
