### ISSUE TITLE
Git pages tests

### ISSUE THREAD

**Issue by marcinch2004** [mhanberg/jekyll-tailwind-starter#14]
Him thanks for fantastic starter package. I have one problem after running it with git pages. I published the page from master and it looks that compiled styles aren't applied. I still have only:

@import "tailwindcss/base";
@import "tailwindcss/components";
@import "_includes/syntax";
@tailwind utilities;

in my CSS (in _site folder it's fine but it looks that git-pages grabs the styles from the root folder)

Please test it if possible.

**Comment by mhanberg** [comment]
I don't believe it's possible to you GitHub Pages with this template, as Tailwind requires using Node.js.

This template is setup to be deployed to [Netlify](https://docs.netlify.com/#discover-netlify), which is also free, hooks up to GitHub, and allows you to use Node.js when building your site.
