### ISSUE TITLE
Compress after purge?

### ISSUE THREAD

**Issue by huphtur** [mhanberg/jekyll-tailwind-starter#2]
Adding cssnano as a PostCSS plugin works, however since tailwind css file is rather large is slows down development whenever a css change is made. Is it possible to add cssnano after the purge?

**Comment by mhanberg** [comment]
@huphtur, I would suggest only running cssnano in production. That can be accomplished by configuring your `postcss.config.js` file like so

```javascript
// postcss.config.js

var plugins = [
    // plugins to run in all environments
];

if (process.env.JEKYLL_ENV === "production") {
  plugins.push(require("cssnano"));
}

module.exports = { plugins: plugins };
```
