### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by jasoncharnes** [mhanberg/jekyll-tailwind-starter#4]
This issue is not an issue, but rather a heartfelt **thank you**. This starter is what I want "to the t" when bootstrapping a Jekyll project with TailwindCSS.

All the ❤️ and 🙌 I can give from Memphis, TN.

**Comment by mhanberg** [comment]
No problem! Thank you for the kind words. 

Make sure you pass those on to the maintainers of jekyll and tailwind!
