### ISSUE TITLE
Reload CSS Imports?

### ISSUE THREAD

**Issue by huphtur** [mhanberg/jekyll-tailwind-starter#5]
Right now when editing some CSS from an include, eg in `_includes/syntax.css` the change is not reflected unless server is restarted. Any way to make that work?

Reason for asking: trying to set up [Build-time imports](https://tailwindcss.com/docs/using-with-preprocessors/#build-time-imports).

**Comment by mhanberg** [comment]
I mistakenly turned on the flag`--incremental` before I updated it to work with Tailwind 1.0, which will only reload pages that actually have changes.

I would make sure to remove that flag from the `bin/start` file and try again.

Side note, `--incremental` works great when you are writing a post, but not good when you are implementing design

**Comment by huphtur** [comment]
[current](https://github.com/mhanberg/jekyll-tailwind-starter/blob/master/bin/start) `bin/start` does not appear to have the `--incremental` flag applied?

**Comment by mhanberg** [comment]
The current one does not, i wanted to make sure that the one you were using didn’t have it set. 

If it’s not that, I’ll have to look more into it, I believe it should recompile.

**Comment by mhanberg** [comment]
I was able to reproduce it, looking into the fix now.

**Comment by huphtur** [comment]
Noticed something else: after making a change to `_includes/syntax.css`, Jekyll rebuilds without any visible changes. Then if right after a change is made to `site.css`, Jekyll rebuilds and the previously made changes to `_includes/syntax.css` are now visible.

**Comment by mhanberg** [comment]
@huphtur I released a new version of jekyll-postcss. Please update that to v0.2.1 and let me know if that fixes your issue.

**Comment by huphtur** [comment]
Can confirm all working. Even tested with different subdirs and Purgecss 👍 👍

**Comment by mhanberg** [comment]
Awesome, thanks for finding this bug!

**Comment by huphtur** [comment]
No, thank YOU for providing this kit, including the jekyll-postcss and jekyll-purgecss gems. And for being extremely responsive to issues.

I added your repo to the [Awesome TailwindCSS](https://github.com/aniftyco/awesome-tailwindcss) list.

Here is [my setup ](https://github.com/huphtur/jekyll-tailwind-starter-plus)of your starter kit (planning to use for a production site very soon).

Thanks again for all your help!
