### ISSUE TITLE
Netlify problems?

### ISSUE THREAD

**Issue by jacobpatton** [mhanberg/jekyll-tailwind-starter#6]
Thanks for setting up this starter app!

I've just forked this repository & tried deploying it to Netlify, and it looks like the Liquid templates aren't getting parsed: https://sleepy-boyd-3e01d0.netlify.com/

(That's without making any changes to your code other than generating the tailwind config file & checking it in.)

Any guesses what I might have screwed up? ;-) Do I need to change any settings at Netlify, perhaps?

Thanks for your help

**Comment by mhanberg** [comment]
@jacobpatton 

I wasn't able to reproduce this. I created a new project and published it to Netlify (https://affectionate-elion-cabaca.netlify.com/) and it works.

Could you try redeploying on Netlify to see if that would fix it?

**Comment by jacobpatton** [comment]
@mhanberg 

Still no luck :-/

I just forked this repository, added it as a new site in Netlify, and got the [same result](https://affectionate-neumann-cba29d.netlify.com/).

Should I change the Netlify defaults after selecting the repository to deploy? Here's how I left them:

<img width="826" alt="netlify" src="https://user-images.githubusercontent.com/3857066/57855324-62653b00-77b8-11e9-887a-118c290a1ba0.png">

Btw, I've also tried deploying both before and after running the `bin/setup` command -- in other words, both with and without the tailwind.config.js file checked in.

**Comment by mhanberg** [comment]
Ah, I think I see the problem.

You need to set the build command to `bundle exec jekyll build` and the publish directory to `_site`.

I think what this is doing is it is rendering the `index.html` file that is in the root of the repo instead of the compiled one from the `_site` directory.

**Comment by jacobpatton** [comment]
Bingo! That fixed it -- thanks for your swift help!
